### ISSUE TITLE
Signup page shouldn't be shown twice

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#1022]
When I sign up and create an account, I can still reach out to the signup page again. This should be limited to 1 signup, which is the admin of the server.

Also, after the signup, the system should take me to the login page directly.

**Comment by ajhollid** [comment]
That's odd, I'm not able to reproduce in normal function.  As long as there is an admin account created you should be directed away from that page.

The only way I'm able to reproduce this is if the BE isn't running so you don't get a response when checking if an admin account exists or not.  In this specific situation there's not much we can do about this, but the user also won't be able to do anything since they're not connected to the BE.

**Comment by Rushi1109** [comment]
> That's odd, I'm not able to reproduce in normal function. As long as there is an admin account created you should be directed away from that page.

Yeah. I can't reproduce this either.

**Comment by ajhollid** [comment]
This turns out to have been an issue with the FE not being able to communicate with the BE.  This behavior is expected
