### ISSUE TITLE
Frontend - Backend Registration Page 

### ISSUE THREAD

**Issue by ajhollid** [bluewave-labs/bluewave-uptime#232]
Registration page should only be shown once to set up admin account

**Comment by ajhollid** [comment]
@danielcj2 @Skorpios604 @MuhammadKhalilzadeh @terryjung0244 Frontend team, opinions on best way to implement this?

I've got an endpoint set up that will return true/false if an admin account exists or not.  I'm not sure the best way to handle the one time registration page though, any thoughts?

**Comment by danielcj2** [comment]
A user technically cannot access the app unless they are logged in so I'd probably have two checks in both the login and registration pages. If there's no admin when logging in, send them over to register. And if there's already an admin when they try to register, just bounce them back to login. An easy way to go about it without inducing too many headaches.

**Comment by Skorpios604** [comment]
I definitely like @danielcj2 idea. It is straight forward and to the point. An alternative to that could possibly be instead of handling redirection based on user actions like the login/registration ect. We can automate the process with middleware or routing logic. So we can create a middleware that checks for the existence of an admin account before rendering any authenticated routes and if there is no admin we can automatically redirect the user to the one time registration page. 

We can also use conditional routing on the frontend based on whether or not an admin account exists.

**Comment by ajhollid** [comment]
@Skorpios604 good points, I was thinking about another ProtectedRoute component's just for the login and register pages that would check for admin, that way we don't have to make an API call to check for admin account on every route

**Comment by Skorpios604** [comment]
Hmm that is actually probably going to be more efficient then. It is also less complex then setting up a middleware.

**Comment by MuhammadKhalilzadeh** [comment]
To achieve a robust one-time admin registration, we can leverage your existing admin existence endpoint. 
Here's my opinion and the approach I guess we're gonna use based on ideas of all you guys, right?  

First, we can utilize React's Context API (like @ajhollid suggested) to create a centralized state for the `adminExists` flag to eliminating redundant API calls. 

A custom ProtectedRoute component (similar to @danielcj2 and @ajhollid ideas) will act as a gatekeeper, conditionally rendering login or registration based on this flag.  

For performance and SEO, we can explore Server-Side Rendering with options we have to pre-render the appropriate page on the server. Finally, secure storage will ensure users only see the registration page once, even after clearing data.
