### ISSUE TITLE
Deploy an AWS server this week.

### ISSUE THREAD

**Issue by Skorpios604** [bluewave-labs/bluewave-uptime#316]
Everyone could login with their own username and pw there. Have a demo server that is the latest release for testing purposes and testing issues immediately. This is something we eventually need to do anyway.

**Comment by ajhollid** [comment]
I think the first step is to start up long running develop and production branches and work off develop going forward instead of master.

Then when we are ready to deploy a release we can merge down to production and deploy that.

Finally we can create some actions to create our docker images and deploy to AWS

**Comment by Skorpios604** [comment]
Ya sounds like a plan

**Comment by ajhollid** [comment]
I think I've got the bugs worked out of the script to get everything going with one command.

I've deployed to my own EC2 box successfully so I think we're good to go here!
