### ISSUE TITLE
Clone a monitor

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#512]
Sometimes it is easier to clone a monitor than to add one from scratch. Just add a "clone" entry to the context menu of a monitor and then when it is selected, a new monitor is added by cloning the current one. 

This is a good first issue for new contributors.

**Comment by geekananya** [comment]
Hi @gorkem-bwl, I would like to work on this issue. Would it be better if on selecting to clone a monitor, the "Create New Monitor" page is opened with all entries pre-filled with configurations of the cloned monitor, so that the user can change the fields as required instead of copying all the configurations as is? This is just a suggestion, I'd be willing to implement it either way you prefer!
