### ISSUE TITLE
When a page speed monitor is added and details are clicked, it cannot find the page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-uptime#618]
**Describe the bug**
When a page speed monitor is added and details are clicked, it cannot find the page. If the data is not populated yet, it should have shown a corresponding notification on the page.

**To Reproduce**
1. Go to Page Speed
2. Click on Create New
3. Create a new Page Speed Monitor
4. Click on the Page Speed Monitor

The following error is shown: 

<img width="479" alt="Screenshot 2024-08-13 at 11 46 09 AM" src="https://github.com/user-attachments/assets/13e6af1c-f13c-40f7-b66f-38ed3e416b74">

**Expected behavior**

Instead of this error, the following error should be shown.

**Working on it!** 

We are still collecting this data. It will be ready momentarily

[Go back to Page speed screen]

**Comment by ajhollid** [comment]
After inspection this issue is caused by unsafe access to data, specifically this block:

```
  useEffect(() => {
    const fetchMonitor = async () => {
      try {
        const res = await axiosInstance.get(
          `/monitors/stats/${monitorId}?sortOrder=desc&limit=50`,
          {
            headers: {
              Authorization: `Bearer ${authToken}`,
            },
          }
        );

        setMonitor(res.data.data);
        setAudits(res.data.data.checks[0].audits);
      } catch (error) {
        console.error("Error fetching pagespeed monitor of id: " + monitorId);
        navigate("/not-found");
      }
    };
 ```

This line `res.data.data.checks[0].audits` and this line `res.data.data` are both unsafe

If a monitor is created it doesn't immediately have any checks associated, so `res.data.data.checks` will be undefined, and trying to access `audits` of undefined` will thrown an error.

This should page should be refactored to ensure robust error handling and graceful failure.
