### ISSUE TITLE
FE - DARK MODE: Styles to fix

### ISSUE THREAD

**Issue by alvarotorrestx** [bluewave-labs/bluewave-uptime#754]
I found that the upload photo is working with the most recent pull, although, I did find that this might have been missed on the possible theme revamp. I understand the theme wasn't fully finished though, but just thought I'd mention it to catch it early. Reference: #748 

![image](https://github.com/user-attachments/assets/3ff07f9b-1fcd-4d07-918c-992b1f5b41c6)

@danielcj2 Is it ok for me to fix it up or would you like to? Also, was it intended this way?

Edit:
Invite team members
![image](https://github.com/user-attachments/assets/53bd64ac-c2f6-4074-b5cd-88bf6d87f6df)

**Comment by danielcj2** [comment]
Yeah there are quite a few broken styles in dark mode. Feel free to fix any as you come across them.

**Comment by ajhollid** [comment]
> I found that the upload photo is working with the most recent pull, although, I did find that this might have been missed on the possible theme revamp. I understand the theme wasn't fully finished though, but just thought I'd mention it to catch it early.

We pushed a fix for the profile image yesterday, so it should be all funcitonal again.  The issue was an axios request that I didn't update properly when I pusehd the networking refactor a couple weeks ago.

Please definitely do open issues for any style problems you come across, we're going to be sorting them out for the next little while as we come across them.

**Comment by ajhollid** [comment]
![image](https://github.com/user-attachments/assets/b69e8dfe-2f9e-4a91-a773-6c12b57d2df2)

Invite page
